# Data

- 8124 Data Points

class: edible(e) or poisonous(p)

cap-shape: bell(b), conical(c), convex(x), flat(f), knobbed(k), sunken(s)

cap-surface: fibrous(f), grooves(g), scaly(y), smooth(s)

cap-color: brown(n), buff(b), cinnamon(c), gray(g), green(r), pink(p), purple(u), red(e), white(w), yellow(y)

bruises: bruises(t), no bruises(f)

odor: almond(a), anise(l), creosote(c), fishy(y), foul(f), musty(m), none(n), pungent(p), spicy(s)

gill-attachment: attached(a), descending(d), free(f), notched(n)

gill-spacing: close(c), crowded(w), distant(d)

gill-size: broad(b), narrow(n)

gill-color: black(k), brown(n), buff(b), chocolate(h), gray(g), green(r), orange(o), pink(p), purple(u), red(e), white(w), yellow(y)

stalk-shape: enlarging(e), tapering(t)

stalk-root: bulbous(b), club(c), cup(u), equal(e), rhizomorphs(z), rooted(r), missing(?)

stalk-surface-above-ring: fibrous(f), scaly(y), silky(k), smooth(s)

stalk-surface-below-ring: fibrous(f), scaly(y), silky(k), smooth(s)

stalk-color-above-ring: brown(n), buff(b), cinnamon(c), gray(g), orange(o), pink(p), red(e), white(w), yellow(y)

stalk-color-below-ring: brown(n), buff(b), cinnamon(c), gray(g), orange(o), pink(p), red(e), white(w), yellow(y)

veil-type: partial(p), universal(u)

veil-color: brown(n), orange(o), white(w), yellow(y)

ring-number: none(n), one(o), two(t)

ring-type: cobwebby(c), evanescent(e), flaring(f), large(l), none(n), pendant(p), sheathing(s), zone(z)

spore-print-color: black(k), brown(n), buff(b), chocolate(h), green(r), orange(o), purple(u), white(w), yellow(y)

population: abundant(a), clustered(c), numerous(n), scattered(s), several(v), solitary(y)

habitat: grasses(g), leaves(l), meadows(m), paths(p), urban(u), waste(w), woods(d)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

%matplotlib inline

In [2]:
df = pd.read_csv("mushrooms.csv")
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

We encode the class(target variable) to numbers and also encode the data (all variables are categorical) to numerical features

In [3]:
le = LabelEncoder()
df['class'] = le.fit_transform(df['class'])

df.head(5)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0      1         x           s         n       t    p               f   
1      0         x           s         y       t    a               f   
2      0         b           s         w       t    l               f   
3      1         x           y         w       t    p               f   
4      0         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
encoded_data = pd.get_dummies(df)

encoded_data.head(5)

class  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0      1            0            0            0            0            0   
1      0            0            0            0            0            0   
2      0            1            0            0            0            0   
3      1            0            0            0            0            0   
4      0            0            0            0            0            0   

   cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s    ...      \
0            1              0              0              1    ...       
1            1              0              0              1    ...       
2            0              0              0              1    ...       
3            1              0              0              0    ...       
4            1              0              0              1    ...       

   population_s  population_v  population_y  habitat_d  habitat_g  habitat_l  \
0             1             0             0          0          0          0   
1             0             0             0          0          1          0   
2             0             0             0          0          0          0   
3             1             0             0          0          0          0   
4             0             0             0          0          1          0   

   habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          1          0  
1          0          0          0          0  
2          1          0          0          0  
3          0          0          1          0  
4          0          0          0          0  

[5 rows x 118 columns]

In [6]:
from sklearn.model_selection import train_test_split

In [8]:
y = df['class'].values.reshape(-1, 1)
X = encoded_data

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Logistic Regression

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn import metrics

In [30]:
logistc_reg = LogisticRegression()

In [31]:
logistc_reg.fit(X_train, y_train.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [32]:
y_pred = logistc_reg.predict(X_test)

In [33]:
print(metrics.confusion_matrix(y_test,y_pred))

[[843   0]
 [  0 782]]


In [34]:
print(metrics.classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       843
          1       1.00      1.00      1.00       782

avg / total       1.00      1.00      1.00      1625



# Linear Discriminant Analysis(LDA)

- LDA aims to find the directions that maximize the separation (or discrimination) between different classes
- LDA tries to determine a suitable feature (sub)space in order to distinguish between patterns that belong to different classes
- Estimate parameters with maximum likelihood (those parameters minimize Squared Mahalanobis Distance)
- Models the distribution of predictors separately in each of the response classes, and then it uses Bayes’ theorem to estimate the probability
- Both LDA and QDA assume the the predictor variables X are drawn from a multivariate Gaussian (aka normal) distribution
- LDA is more suitable for smaller data sets, and it has a higher bias, and a lower variance. (compared to QDA)
- If n is small and the distribution of the predictors X is approximately normal in each of the classes, the LDA model is more stable than logistic.
- When the classes are well-separated, the parameter estimates for the logistic model are surprisingly unstable. LDA does not suffer from this.
- These classifiers(LDA, QDA) are attractive because they have closed-form solutions that can be easily computed, are inherently multiclass, have proven to work well in practice, and have no hyper-parameters to tune.

In [14]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [15]:
lda = LinearDiscriminantAnalysis()

In [16]:
lda.fit(X_train, y_train.ravel())

C:\Users\josh\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

In [35]:
y_pred_lda = lda.predict(X_test)

In [37]:
metrics.confusion_matrix(y_test,y_pred_lda)

array([[843,   0],
       [  0, 782]], dtype=int64)

In [38]:
print(metrics.classification_report(y_test,y_pred_lda))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       843
          1       1.00      1.00      1.00       782

avg / total       1.00      1.00      1.00      1625



# Quadratic Discriminant Analysis (QDA)

- A classifier with a quadratic decision boundary, generated by fitting class conditional densities to the data and using Bayes’ rule.
- The model fits a Gaussian density to each class.
- QDA is a better option for large data sets (compared to LDA), as it tends to have a lower bias and a higher variance.

In [41]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [42]:
qda = QuadraticDiscriminantAnalysis()

In [46]:
qda.fit(X_train, y_train.ravel())

C:\Users\josh\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:682: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariance=False, store_covariances=None, tol=0.0001)

In [47]:
y_pred_qda = qda.predict(X_test)

In [48]:
metrics.confusion_matrix(y_test,y_pred_qda)

array([[843,   0],
       [  0, 782]], dtype=int64)

In [49]:
print(metrics.classification_report(y_test,y_pred_qda))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       843
          1       1.00      1.00      1.00       782

avg / total       1.00      1.00      1.00      1625

